docs: start a developer's doc with a tip related to building sambacc dev branches
samba-in-kubernetes/samba-container pull request #156
Opened 2023-08-10 22:51 UTC by phlogistonjohn

While hacking on a some sambacc stuff I realized I had not written down the technique I used to build samba-container images that use work-in-progress sambacc code and had to partially re-invent it. Fix one issue I found while doing that and start a developers guide document by documenting this  process that I used to test out development branches of sambacc in a proper samba-container image.

2023-08-13 12:17 UTC, synarete submitted a review, later dismissed
lgtm

2023-08-14 11:24 UTC, obnoxxx requested changes
This is a great start of a developer doc! Not entirely done with my review yet, but already suggesting a few wording chandes ...

2023-08-14 11:24 UTC, obnoxxx commented on docs/development.md
> +When developing sambacc there are a suite of unit tests but that often not
```suggestion
Changes to  `sambacc` are validated by  a suite of unit tests but that is often not
```

2023-08-14 11:24 UTC, obnoxxx commented on docs/development.md
> +enough. One may want to try out a unreleased branch of sambacc code as
```suggestion
enough to ensure  a minimum level of quality for use in samba container images. One may nonetheless want to try out an unreleased branch of sambacc code as
```

2023-08-14 17:21 UTC, phlogistonjohn commented on docs/development.md
> +When developing sambacc there are a suite of unit tests but that often not
done

2023-08-14 17:21 UTC, phlogistonjohn commented on docs/development.md
> +enough. One may want to try out a unreleased branch of sambacc code as
adapted

2023-08-14 17:22 UTC, phlogistonjohn commented on docs/development.md
> +and available at quay.io: quay.io/samba.org/sambacc
loosely adapted

2023-08-14 17:57 UTC, obnoxxx approved these changes
Thanks for the update addressing the requests! LGTM

2023-08-15 08:09 UTC, synarete approved these changes
lgtm

2023-08-15 09:05 UTC, obnoxxx commented
one ci check failure remains, but it can not be caused by this doc-only PR. should we merge manually with override, @synarete , @anoopcs9 ?

2023-08-15 11:41 UTC, merged