hack: extract release script to generate download info from  the release doc
samba-in-kubernetes/samba-container pull request #187
Opened 2024-11-27 11:28 UTC by obnoxxx

This extracts the  script added to the the release process document as in PR #185 from the document.

This script can be invoked to create the downloads section for the release notes for a given release.

2024-11-28 06:48 UTC, anoopcs9 requested changes

2024-11-28 06:48 UTC, anoopcs9 commented on hack/release-gen-download-section.sh
> +    final_tag=${1//pre[0-9]*//}
```suggestion
    final_tag=${2/%pre[0-9]*/}
```

2024-11-29 17:30 UTC, phlogistonjohn commented
Sorry @obnoxxx but I didn't really mean to make this a fully fledged script. It was more meant as a template someone running the release can use.

2024-12-05 09:16 UTC, obnoxxx commented
@phlogistonjohn  wrote:
> Sorry @obnoxxx but I didn't really mean to make this a fully fledged script. It was more meant as a template someone running the release can use.

 Understood, but I thought that having to copy and paste from the doc lacks a level of convenience that providing an actual script offers.

2025-01-07 13:31 UTC, obnoxxx commented
@phlogistonjohn  wrote:

> Sorry @obnoxxx but I didn't really mean to make this a fully fledged script. It was more meant as a template someone running the release can use.

I still think that an actual script in the repo adds more real convenience than a copy-and-paste template which is better than no automation but clumsy to use at best (IMHO).

since you are opposed to having this, @phlogistonjohn), should I just go ahead and close this PR?

2025-01-08 05:17 UTC, anoopcs9 commented
> @anoopcs9, github says that you requested changes but I can't see any more what it was that you requested.

Because my previous [suggestion](https://github.com/samba-in-kubernetes/samba-container/pull/187#discussion_r1861593995) was resolved without making any changes in the updated version. I've "unresolved" it for now. Let me know what you think.

2025-01-08 09:37 UTC, obnoxxx commented
@anoopcs9  wrote:
> > @anoopcs9, github says that you requested changes but I can't see any more what it was that you requested.
> 
> Because my previous [suggestion](https://github.com/samba-in-kubernetes/samba-container/pull/187#discussion_r1861593995) was resolved without making any changes in the updated version. I've "unresolved" it for now. Let me know what you think.

Thanks for clarifying!
I have nowapplied and squashed your suggestion.

2025-01-08 10:22 UTC, anoopcs9 approved these changes
lgtm, thanks.

2025-01-08 10:23 UTC, merged

2025-01-08 10:26 UTC, anoopcs9 commented
@phlogistonjohn @obnoxxx 
Sorry, I forgot that this had a `priority-review` label which now requires just 1 approval.

2025-01-08 13:06 UTC, phlogistonjohn commented
It's fine. Like I said earlier: I didn't think making a full script was worth the effort... but I am ok with it if enough others wanted it.