examples: add a yaml for smbd+winbind pod
samba-in-kubernetes/samba-container pull request #21
Opened 2021-02-03 21:25 UTC by phlogistonjohn

This adds a basic, but functional, example of running a pod in kubernetes with both sbmd and winbind for use as a domain member smb server.

The YAML contains a ConfigMap, secret, and pod configuration. One must edit parts of the yaml (and the embedded JSON) to match the  user's domain.

This currently needs a new build of the samba server container to work thus it won't work without the commit bumping the version of sambacc in use. If you want I can split these into separate PRs. I wasn't sure if that was needed as this is "just" an example.

2021-02-03 23:23 UTC, obnoxxx requested changes
small typo

2021-02-03 23:23 UTC, obnoxxx commented on examples/kubernetes/sambadmpod.yml
> +# Configuration for thae samba domain member pod.
```suggestion
# Configuration for the samba domain member pod.
```

2021-02-04 13:54 UTC, phlogistonjohn commented on examples/kubernetes/sambadmpod.yml
> +# Configuration for thae samba domain member pod.
Fixed.

2021-02-04 18:20 UTC, obnoxxx approved these changes
lgtm

2021-02-04 18:20 UTC, merged