images/client: add 'samba-test'
samba-in-kubernetes/samba-container pull request #83
Opened 2022-11-10 12:39 UTC by synarete

Allow using the samba-client image for testing, via the 'smbtorture' utility.

Signed-off-by: Shachar Sharon <ssharon@redhat.com>

2022-11-10 14:31 UTC, synarete commented
> Thinking out loud: would this be better in a separate image? While it's nice not to have to manage lots of images we're asking every consumer of a samba client image to also carry around stuff that's only useful to those testing samba. Basically, is the samba client image meant more for our own testing or do we want it to be for a broader audience? Note that neither choice is set in stone - we can decide that for now, the image is more for us, but if more consumers of the image come along we can split things up in the future. -- Food for thought, especially while the PR is still draft :-)

I follow the same line of thought, which is why I turned this PR into draft. Still not sure which option is the best.

2022-11-11 15:29 UTC, phlogistonjohn commented
Sounds good to me, having a specific "toolbox" image would be a clean approach.

2022-11-13 11:34 UTC, synarete commented
> Sounds good to me, having a specific "toolbox" image would be a clean approach.

See: https://github.com/samba-in-kubernetes/samba-container/pull/84

2022-11-22 17:45 UTC, obnoxxx requested changes
please rebase and resolve conflicts.

did you mean to add smbtorture instead of samba-test?

2022-11-23 07:23 UTC, synarete commented
> please rebase and resolve conflicts.
> 
> did you mean to add smbtorture instead of samba-test?

@obnoxxx  'samba-test' is the name of the rpm package which contains smbtorture. In all odds, this PR has changed to draft, as we decided to use a different image for toolbox (which will be based of samba-client image).

2022-11-23 07:24 UTC, closed without merging

2022-11-23 17:54 UTC, obnoxxx commented
> > please rebase and resolve conflicts.
> > did you mean to add smbtorture instead of samba-test?
> 
> @obnoxxx 'samba-test' is the name of the rpm package which contains smbtorture. In all odds, this PR has changed to draft, as we decided to use a different image for toolbox (which will be based of samba-client image).

@synarete , thanks for the explanation. it all looks good, and the toolbox PR #84 is merged now