client: use fedora36 as base image
samba-in-kubernetes/samba-container pull request #85
Opened 2022-11-22 09:23 UTC by synarete

Align client to same base image as server and ad-server, as well as base image used by sambacc. Allows the container engine to share image-layers between containers.

Signed-off-by: Shachar Sharon <ssharon@redhat.com>

2022-11-22 15:57 UTC, phlogistonjohn approved these changes
LGTM, thanks!

2022-11-22 15:58 UTC, phlogistonjohn commented
@synarete I'll let you merge the PRs of this and #86 so that you can choose to have whichever one you prefer merged first. :-)

2022-11-22 17:37 UTC, obnoxxx reviewed
lgtm

2022-11-22 17:39 UTC, obnoxxx approved these changes

2022-11-22 17:43 UTC, obnoxxx requested changes
now that #86 has merged, this has conflicts that need resolving when rebasing... withdrawing my previous approval. in general, modulo the conflicy, thil looks good

2022-11-23 10:21 UTC, anoopcs9 approved these changes

2022-11-23 11:18 UTC, obnoxxx commented
> @synarete I'll let you merge the PRs of this and #86 so that you can choose to have whichever one you prefer merged first. :-)

Apologies: I merged #86 without giving anyone a chance to react to this, thereby creating rebase conflicts ...

2022-11-23 11:18 UTC, obnoxxx approved these changes
lgtm, thanks for the rebase!

2022-11-23 11:18 UTC, merged